FROM python:3.10

WORKDIR /usr/app

ADD ./api/service_movies/requirements.txt .
RUN pip install -r requirements.txt

EXPOSE 5000

ENTRYPOINT [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload", "--log-level", "debug" ]