version: "3"

services:
  # DATABASES
  redis:
    container_name: redis
    build:
      dockerfile: redis/Dockerfile
      context: ./
    restart: unless-stopped
    command: [ "redis-server" ]
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    networks:
      - api

  mongo:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    restart: unless-stopped
    command: mongod --auth
    expose:
      - "27017"
    env_file: .env
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGODB_DATA_DIR: ./volumes/db
      MONGODB_LOG_DIR: /dev/null
    networks:
      - databases
      - api
      - kafka-network

  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_URL}
    depends_on:
      - mongo
    networks:
      - databases

  tmdb-producer:
    container_name: tmdb-producer
    restart: on-failure
    command: python3 -u ./tmdb_producer.py
    build:
      dockerfile: kafka/producer/Dockerfile
      context : .
    depends_on:
      kafka:
        condition: service_healthy
      tmdb-consumer:
        condition: service_started
    networks:
      - api
      - kafka-network

  tmdb-consumer:
    container_name: tmdb-consumer
    restart: on-failure
    command: python3 -u ./tmdb_consumer.py
    build:
      dockerfile: kafka/consumer/Dockerfile
      context: .
    depends_on:
      kafka:
        condition: service_healthy
      mongo:
        condition: service_started
    networks:
      - kafka-network

  twitter-producer:
    container_name: twitter-producer
    restart: on-failure
    command: python3 -u ./twitter_producer.py
    build:
      dockerfile: kafka/producer/Dockerfile
      context: .
    depends_on:
      kafka:
        condition: service_healthy
      twitter-consumer:
        condition: service_started
    networks:
      - api
      - kafka-network

  twitter-consumer:
    container_name: twitter-consumer
    restart: on-failure
    command: python3 -u ./twitter_consumer.py
    build:
      dockerfile: kafka/consumer/Dockerfile
      context: .
    depends_on:
      kafka:
        condition: service_healthy
      mongo:
        condition: service_started
    networks:
      - kafka-network
  
  rss-producer:
    container_name: rss-producer
    restart: on-failure
    command: python3 -u ./rss_producer.py
    build:
      dockerfile: kafka/producer/Dockerfile
      context : .
    depends_on:
      kafka:
        condition: service_healthy
      rss-consumer:
        condition: service_started
    networks:
      - kafka-network
      
  rss-consumer:
    container_name: rss-consumer
    command: python3 -u ./rss_consumer.py
    restart: on-failure
    build:
      dockerfile: kafka/consumer/Dockerfile
      context : .
    depends_on:
      kafka:
        condition: service_healthy
      mongo:
        condition: service_started
    networks:
      - kafka-network

  pipeline-ml:
    container_name: pipeline-ml
    build:
      dockerfile: pipeline-ml/Dockerfile
      context: .
    depends_on:
      - mongo
    networks:
      - databases

  api-movies:
    container_name: api-movies
    build:
      context: ./
      dockerfile: api/DockerFile
    volumes:
      - ./api:/app
    ports:
      - 5000:443
    depends_on:
      - mongo
    networks:
      - kafka-network

  # KAFKA
  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_CREATE_TOPICS: tmdb,twitter,rss
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
    healthcheck:
      test:
        [
          "CMD",
          "bash",
          "-c",
          "unset",
          "JMX_PORT",
          ";",
          "/bin/kafka-topics.sh",
          "--bootstrap-server",
          "localhost:29092",
          "--list"
        ]
      interval: 20s
      timeout: 10s
      retries: 4
    expose:
      - "29092"
      - "9092"
      - "30001"
    networks:
      - kafka-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-network

  # UI
  # interface:
  #   container_name: interface
  #   build:
  #     context: ./
  #     dockerfile: interface/Dockerfile
  #   volumes:
  #     - ./interface:/app
  #   ports:
  #     - 8080:3000
  #   depends_on:
  #     - api-movies


networks:
  databases:
  api:
  kafka-network:


volumes:
  mongo:
  redis_data:
