FROM python:3.10

WORKDIR /app

COPY api/. /app/
RUN pip install -r requirements.txt

EXPOSE 80
EXPOSE 443

ENTRYPOINT [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "443", "--ssl-keyfile", "/app/ssl/private.key", "--ssl-certfile", "/app/ssl/certificate.crt", "--ssl-keyfile-password", "apimovies", "--reload", "--log-level", "debug" ]