From python:3.11.2-alpine

WORKDIR /app

ADD requirements.txt .

RUN pip install -r requirements.txt

ADD ./service_movies .

EXPOSE 8080

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload", "--log-level", "debug"]
